In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('DirtyData.csv')

data

    Duration          Date  Pulse  Maxpulse  Calories
0     0         60  '2020/12/01'    110       130 ...
1     1         60  '2020/12/02'    117       145 ...
2     2         60  '2020/12/03'    103       135 ...
3     3         45  '2020/12/04'    109       175 ...
4     4         45  '2020/12/05'    117       148 ...
5     5         60  '2020/12/06'    102       127 ...
6     6         60  '2020/12/07'    110       136 ...
7     7        450  '2020/12/08'    104       134 ...
8     8         30  '2020/12/09'    109       133 ...
9     9         60  '2020/12/10'     98       124 ...
10    10        60  '2020/12/11'    103       147 ...
11    11        60  '2020/12/12'    100       120 ...
12    12        60  '2020/12/12'    100       120 ...
13    13        60  '2020/12/13'    106       128 ...
14    14        60  '2020/12/14'    104       132 ...
15    15        60  '2020/12/15'     98       123 ...
16    16        60  '2020/12/16'     98       120 ...
17    17        60  '2020/12/17'    100       120 ...
18    18        45  '2020/12/18'     90       112 ...
19    19        60  '2020/12/19'    103       123 ...
20    20        45  '2020/12/20'     97       125 ...
21    21        60  '2020/12/21'    108       131 ...
22    22        45           NaN    100       119 ...
23    23        60  '2020/12/23'    130       101 ...
24    24        45  '2020/12/24'    105       132 ...
25    25        60  '2020/12/25'    102       126 ...
26    26        60    2020/12/26    100       120 ...
27    27        60  '2020/12/27'     92       118 ...
28    28        60  '2020/12/28'    103       132 ...
29    29        60  '2020/12/29'    100       132 ...
30    30        60  '2020/12/30'    102       129 ...
31    31        60  '2020/12/31'     92       115 ...